"""Docker image builder for ComfyUI containers."""

import subprocess
from pathlib import Path

from models import ModelInfo
from settings import Settings


def generate_dockerfile(
    base_image: str,
    selected_models: list[ModelInfo],
    output_path: Path
) -> str:
    """Generate a Dockerfile with selected models.
    
    Args:
        base_image: Base Docker image to use
        selected_models: List of models to include
        output_path: Path to write the Dockerfile
        
    Returns:
        The generated Dockerfile content
    """
    lines = [
        f"# ComfyUI with custom models",
        f"# Auto-generated by ComfyUI Container Builder",
        f"FROM {base_image}",
        "",
        "USER root",
        "",
    ]
    
    # Group models by destination for cleaner output
    for model in selected_models:
        lines.append(f"# {model.name} ({model.size_gb:.1f} GB)")
        lines.append(f"RUN wget -q --show-progress -O /opt/comfyui/models/{model.destination}/{model.filename} \\")
        lines.append(f'    "{model.url}"')
        lines.append("")
    
    lines.extend([
        "# Set proper ownership",
        "RUN chown -R comfyui:comfyui /opt/comfyui/models",
        "",
        "USER comfyui",
        "",
        "# Enable TAESD previews by default",
        "ENV PREVIEW_METHOD=taesd",
    ])
    
    content = "\n".join(lines)
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(content)
    
    return content


def build_image(
    dockerfile_path: Path,
    image_tag: str,
    on_output: callable | None = None
) -> tuple[bool, str]:
    """Build a Docker image.
    
    Args:
        dockerfile_path: Path to the Dockerfile
        image_tag: Tag for the built image
        on_output: Callback for build output lines
        
    Returns:
        Tuple of (success, message)
    """
    try:
        process = subprocess.Popen(
            ["docker", "build", "-f", str(dockerfile_path), "-t", image_tag, str(dockerfile_path.parent)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
        
        output_lines = []
        for line in iter(process.stdout.readline, ""):
            output_lines.append(line.rstrip())
            if on_output:
                on_output(line.rstrip())
        
        process.wait()
        
        if process.returncode == 0:
            return True, f"Successfully built {image_tag}"
        else:
            return False, f"Build failed with exit code {process.returncode}"
            
    except FileNotFoundError:
        return False, "Docker not found. Please install Docker."
    except Exception as e:
        return False, f"Build error: {e}"


def push_to_ecr(
    image_tag: str,
    ecr_registry: str,
    ecr_region: str,
    on_output: callable | None = None
) -> tuple[bool, str]:
    """Push image to ECR.
    
    Args:
        image_tag: Local image tag
        ecr_registry: ECR registry URL
        ecr_region: AWS region
        on_output: Callback for output lines
        
    Returns:
        Tuple of (success, message)
    """
    if not ecr_registry:
        return False, "ECR registry not configured. Please set it in Settings."
    
    ecr_tag = f"{ecr_registry}/{image_tag}"
    
    try:
        # Login to ECR
        if on_output:
            on_output("Logging in to ECR...")
        
        login_cmd = f"aws ecr get-login-password --region {ecr_region} | docker login --username AWS --password-stdin {ecr_registry}"
        result = subprocess.run(login_cmd, shell=True, capture_output=True, text=True)
        
        if result.returncode != 0:
            return False, f"ECR login failed: {result.stderr}"
        
        # Tag image
        if on_output:
            on_output(f"Tagging image as {ecr_tag}...")
        
        result = subprocess.run(["docker", "tag", image_tag, ecr_tag], capture_output=True, text=True)
        if result.returncode != 0:
            return False, f"Tagging failed: {result.stderr}"
        
        # Push image
        if on_output:
            on_output(f"Pushing to {ecr_tag}...")
        
        process = subprocess.Popen(
            ["docker", "push", ecr_tag],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )
        
        for line in iter(process.stdout.readline, ""):
            if on_output:
                on_output(line.rstrip())
        
        process.wait()
        
        if process.returncode == 0:
            return True, f"Successfully pushed to {ecr_tag}"
        else:
            return False, f"Push failed with exit code {process.returncode}"
            
    except Exception as e:
        return False, f"Push error: {e}"
